version: "3.9"

services:
  php:
    # image: dunglas/frankenphp
    build:
      context: .
    container_name: frankenphp
    restart: always
    ports:
      - "18000:80" # HTTP
      #- "18001:443" # HTTPS
      #- "18001:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    depends_on:
      - pgsql
      # - redis

  pgsql:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   volumes:
  #     - redis_data:/data

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  redis_data:
